### ISSUE TITLE
Segfaulting on simple example in the documentation

### ISSUE THREAD

**Issue by fccoelho** [neurophysik/jitcode#25] opened 2020-12-09 16:54 UTC
Hi I am trying to run a simple example from the documentation but the compiled code just segfaults. this is the example:

```python
from jitcode import jitcode, y
import numpy as np
from time import time
import pylab as P
from scipy.integrate import odeint

a  = -0.025794
b1 =  0.0065
b2 =  0.0135
c  =  0.02
k  =  0.128

f = [
	y(0) * ( a-y(0) ) * ( y(0)-1.0 ) - y(1) + k * (y(2) - y(0)),
	b1*y(0) - c*y(1),
	y(2) * ( a-y(2) ) * ( y(2)-1.0 ) - y(3) + k * (y(0) - y(2)),
	b2*y(2) - c*y(3)
	]

initial_state = np.array([1.,2.,3.,4.])

# Jitcode implementation

ODE = jitcode(f)
ODE.set_integrator("dopri5")
ODE.set_initial_value(initial_state,0.0)

times = 2000+np.arange(100000)
data = []
for time in times:
	data.append(ODE.integrate(time))

```
githu
What can I do to work around this issue? also where is the compiled code saved?

**Comment by fccoelho** [comment] 2020-12-09 17:49
Funny enough, I can get it to compile and run under VSCode debugger, but not on a straight run!

here is the updated code:
```python
from jitcode import jitcode, y
import numpy as np
from time import time
import pylab as P
from scipy.integrate import odeint

γ = 0.6
φ = 1.0
ω = 0.5
ν = 0.5

R,B = dynvars = [ y(i) for i in range(2) ]

lotka_volterra_diff = {
		B:  γ*B - φ*R*B,
		R: -ω*R + ν*R*B,
	}

ODE = jitcode(lotka_volterra_diff)
ODE.set_integrator("dopri5")
initial_state = { R: 0.2, B: 0.5 }
ODE.set_initial_value(initial_state,0.0)

times = np.arange(0.0,5000,0.1)
values = { R: [], B: [] }
t0 = time()
for t in times:
	ODE.integrate(t)
	for dynvar in dynvars:
		values[dynvar].append(ODE.y_dict[dynvar])
print(f'Jitcode model ran in {time()-t0} seconds')

def lotka(y,t,*pars):
    R,B = y
    return [
        γ*B - φ*R*B,
        -ω*R + ν*R*B
    ]

t0 = time()
res = odeint(lotka,[0.2,0.5],times)
print(f'Odeint model ran in {time()-t0} seconds')
```
But it is about ten times slower than odeint!

```
Generating, compiling, and loading C code.
generated C code for f
Jitcode model ran in 1.960545539855957 seconds
Odeint model ran in 0.24532318115234375 seconds
```

**Comment by Wrzlprmft** [comment] 2020-12-10 11:37
### The segmentation fault

I first changed your code such that it compiles with debug symbols and doesn’t delete the temporary directory on exit in which the code is stored, but prints it:

```
from jitcode import jitcode, y
import numpy as np
from jitcxde_common import DEFAULT_COMPILE_ARGS

# Avoid temporary directory being deleted:
jitcode.__del__ = lambda self: None

a  = -0.025794
b1 =  0.0065
b2 =  0.0135
c  =  0.02
k  =  0.128

f = [
	y(0) * ( a-y(0) ) * ( y(0)-1.0 ) - y(1) + k * (y(2) - y(0)),
	b1*y(0) - c*y(1),
	y(2) * ( a-y(2) ) * ( y(2)-1.0 ) - y(3) + k * (y(0) - y(2)),
	b2*y(2) - c*y(3)
	]

initial_state = np.array([1.,2.,3.,4.])

ODE = jitcode(f)

# Compile with debug symbols:
ODE.compile_C( extra_compile_args = DEFAULT_COMPILE_ARGS + ["-g","-UNDEBUG","-O0"] )
ODE.set_integrator("dopri5")
ODE.set_initial_value(initial_state,0.0)

times = 100+np.arange(100)
data = []
for time in times:
	data.append(ODE.integrate(time))

print(ODE._tmpdir)
```

I then ran this with Valgrind to see whether there anything happens that could be causing a segmentation fault (as those do not happen every time). Valgrind did not find anything related to the JiTCODE-generated code (there are tons of messages caused by Python internals, but that’s normal and no cause for concern).

This suggests that the issue in question is specific to your compiler or some other aspect of your setup. For resolving this, I would appreciate if you installed Valgrind, get [this file](https://svn.python.org/projects/python/trunk/Misc/valgrind-python.supp) and run it like this:

```
valgrind --suppressions=valgrind-python.supp --log-file=valgrind.log  python3 bug.py
```

Then please report to me any reports (consisting of 20–60 lines) in `valgrind.log` that explicitly mention `jitced.c`.

> Funny enough, I can get it to compile and run under VSCode debugger, but not on a straight run!

This is not too surprising. Segmentation faults usually can only be detected if a program tries to access memory that it doesn’t own. Depending on how exactly your system allocates memory to the program, this may turn a faulty memory access into an internal one (which is still faulty, but not detectable). Thus the very same deterministic, autonomous program may run on the same system once with a segmentation fault being detected and once without, just because the memory landscape is different. Moreover, debugging considerably changes how things are handled.

### Runtime

> But it is about ten times slower than odeint!

This is not surprising given that you have a low-dimensional problem with a high sampling frequency. In such a situation, most of the work happens in the input and output, which is more streamlined in ODEInt for the price of not having a fine-grained control of integration steps. For higher-dimensional systems (for which JiTCODE was optimised), the interfacing costs become negligible and calculating the derivative is the main runtime sink.

**Comment by fccoelho** [comment] 2020-12-10 13:17
This 4D model compiled and ran just fine on my computer. About the performance, I was hoping that JiTCODE would eliminate the python function call overhead one has in `odeint`. It seems that nowadays this overhead is not that big anymore. 

Here is the valgrind log of the lotka-volterra model.

[valgrind.log](https://github.com/neurophysik/jitcode/files/5672921/valgrind.log)

**Comment by Wrzlprmft** [comment] 2020-12-11 10:27
> This 4D model compiled and ran just fine on my computer. About the performance, I was hoping that JiTCODE would eliminate the python function call overhead one has in `odeint`. It seems that nowadays this overhead is not that big anymore.

No, the Python function calls could only be eliminated by doing everything in a monolithic C code. If this overhead is a relevant bottleneck for you, I doubt that there will be any existing Python solution that helps you. JiTC**D**DE has a more direct connection between integrator and derivative, but the integrator used is not the best for ODEs and it is still operated from Python.

> Here is the valgrind log of the lotka-volterra model.
> 
> [valgrind.log](https://github.com/neurophysik/jitcode/files/5672921/valgrind.log)

This is very weird. The problem seems to happen in [QT](https://en.wikipedia.org/wiki/Qt_(software)), which is not only completely out of my reach and expertise, but also should not be involved here at all (and indeed isn’t in any of the reports except those directly preceding it). Are you running all of this in some programming environment or similar?

**Comment by fccoelho** [comment] 2020-12-11 10:57
Thanks for the information. Regarding Qt, I don't know where it comes from. I am running it from the terminal. My desktop environment is KDE which is based on Qt, but it should not affect it. But I re-ran it completely outside the graphical environment and generated this second log:
[valgrind.log](https://github.com/neurophysik/jitcode/files/5678738/valgrind.log)

I hope it helps.

**Comment by Wrzlprmft** [comment] 2020-12-11 11:02
Did that one finish without a segmentation fault? Because I see no indication of a lethal error or a termination in the log.

**Comment by fccoelho** [comment] 2020-12-11 11:39
It did, but when I run it without valgrind it still segfaults.

**Comment by Wrzlprmft** [comment] 2020-12-11 17:04
What a sneaky bug! I will think about how to hunt this one down, but so far everything points to it not being my fault.

**Comment by Wrzlprmft** [comment] 2021-07-11 14:27
If this is still an issue, can you try updating SymEngine? It was responsible for similar bugs (see e.g., [this issue](https://github.com/neurophysik/jitcdde/issues/35)).

**Closed** 2022-03-05 16:09 UTC
